data3 = [{'code3': 'ABW', 'name': 'Aruba', 'value': 4.78, 'code': 'AW'},
{'code3': 'AFG', 'name': 'Afghanistan', 'value': 6.8, 'code': 'AF'},
{'code3': 'AGO', 'name': 'Angola', 'value': 6.06, 'code': 'AO'},
{'code3': 'ALB', 'name': 'Albania', 'value': 6.59, 'code': 'AL'},
{'code3': 'AND', 'name': 'Andorra', 'value': 4.57, 'code': 'AD'},
{'code3': 'ARE', 'name': 'United Arab Emirates', 'value': 5.93, 'code': 'AE'},
{'code3': 'ARG', 'name': 'Argentina', 'value': 6.11, 'code': 'AR'},
{'code3': 'ARM', 'name': 'Armenia', 'value': 6.54, 'code': 'AM'},
{'code3': 'ASM', 'name': 'American Samoa', 'value': 'No Data', 'code': 'AS'},
{'code3': 'ATG',
 'name': 'Antigua and Barbuda',
 'value': 'No Data',
 'code': 'AG'},
{'code3': 'AUS', 'name': 'Australia', 'value': 5.76, 'code': 'AU'},
{'code3': 'AUT', 'name': 'Austria', 'value': 6.24, 'code': 'AT'},
{'code3': 'AZE', 'name': 'Azerbaijan', 'value': 7.23, 'code': 'AZ'},
{'code3': 'BDI', 'name': 'Burundi', 'value': 'No Data', 'code': 'BI'},
{'code3': 'BEL', 'name': 'Belgium', 'value': 6.15, 'code': 'BE'},
{'code3': 'BEN', 'name': 'Benin', 'value': 'No Data', 'code': 'BJ'},
{'code3': 'BFA', 'name': 'Burkina Faso', 'value': 6.9, 'code': 'BF'},
{'code3': 'BGD', 'name': 'Bangladesh', 'value': 7.16, 'code': 'BD'},
{'code3': 'BGR', 'name': 'Bulgaria', 'value': 6.58, 'code': 'BG'},
{'code3': 'BHR', 'name': 'Bahrain', 'value': 5.92, 'code': 'BH'},
{'code3': 'BHS', 'name': 'Bahamas, The', 'value': 'No Data', 'code': 'BS'},
{'code3': 'BIH',
 'name': 'Bosnia and Herzegovina',
 'value': 6.64,
 'code': 'BA'},
{'code3': 'BLR', 'name': 'Belarus', 'value': 6.25, 'code': 'BY'},
{'code3': 'BLZ', 'name': 'Belize', 'value': 4.2, 'code': 'BZ'},
{'code3': 'BMU', 'name': 'Bermuda', 'value': 5.2, 'code': 'BM'},
{'code3': 'BOL', 'name': 'Bolivia', 'value': 6.26, 'code': 'BO'},
{'code3': 'BRA', 'name': 'Brazil', 'value': 6.07, 'code': 'BR'},
{'code3': 'BRB', 'name': 'Barbados', 'value': 'No Data', 'code': 'BB'},
{'code3': 'BRN',
 'name': 'Brunei Darussalam',
 'value': 'No Data',
 'code': 'BN'},
{'code3': 'BTN', 'name': 'Bhutan', 'value': 7.07, 'code': 'BT'},
{'code3': 'BWA', 'name': 'Botswana', 'value': 7.1, 'code': 'BW'},
{'code3': 'CAF',
 'name': 'Central African Republic',
 'value': 'No Data',
 'code': 'CF'},
{'code3': 'CAN', 'name': 'Canada', 'value': 5.57, 'code': 'CA'},
{'code3': 'CHE', 'name': 'Switzerland', 'value': 6.28, 'code': 'CH'},
{'code3': 'CHL', 'name': 'Chile', 'value': 5.79, 'code': 'CL'},
{'code3': 'CHN', 'name': 'China', 'value': 6.07, 'code': 'CN'},
{'code3': 'CIV', 'name': "Cote d'Ivoire", 'value': 'No Data', 'code': 'CI'},
{'code3': 'CMR', 'name': 'Cameroon', 'value': 6.92, 'code': 'CM'},
{'code3': 'COD',
 'name': 'Congo, Dem. Rep.',
 'value': 6.3,
 'code': 'CD'},
{'code3': 'COG', 'name': 'Congo, Rep.', 'value': 4.72, 'code': 'CG'},
{'code3': 'COL', 'name': 'Colombia', 'value': 6.21, 'code': 'CO'},
{'code3': 'COM', 'name': 'Comoros', 'value': 'No Data', 'code': 'KM'},
{'code3': 'CPV', 'name': 'Cabo Verde', 'value': 'No Data', 'code': 'CV'},
{'code3': 'CRI', 'name': 'Costa Rica', 'value': 5.93, 'code': 'CR'},
{'code3': 'CUB', 'name': 'Cuba', 'value': 6.41, 'code': 'CU'},
{'code3': 'CUW', 'name': 'Curacao', 'value': 'No Data', 'code': 'CW'},
{'code3': 'CYM', 'name': 'Cayman Islands', 'value': 6.16, 'code': 'KY'},
{'code3': 'CYP', 'name': 'Cyprus', 'value': 6.05, 'code': 'CY'},
{'code3': 'CZE', 'name': 'Czech Republic', 'value': 6.02, 'code': 'CZ'},
{'code3': 'DEU', 'name': 'Germany', 'value': 6.1, 'code': 'DE'},
{'code3': 'DJI', 'name': 'Djibouti', 'value': 4.0, 'code': 'DJ'},
{'code3': 'DMA', 'name': 'Dominica', 'value': 'No Data', 'code': 'DM'},
{'code3': 'DNK', 'name': 'Denmark', 'value': 6.0, 'code': 'DK'},
{'code3': 'DOM', 'name': 'Dominican Republic', 'value': 6.19, 'code': 'DO'},
{'code3': 'DZA', 'name': 'Algeria', 'value': 6.46, 'code': 'DZ'},
{'code3': 'ECU', 'name': 'Ecuador', 'value': 6.48, 'code': 'EC'},
{'code3': 'EGY',
 'name': 'Egypt, Arab Rep.',
 'value': 6.14,
 'code': 'EG'},
{'code3': 'ESP', 'name': 'Spain', 'value': 5.88, 'code': 'ES'},
{'code3': 'EST', 'name': 'Estonia', 'value': 6.26, 'code': 'EE'},
{'code3': 'ETH', 'name': 'Ethiopia', 'value': 6.56, 'code': 'ET'},
{'code3': 'FIN', 'name': 'Finland', 'value': 5.92, 'code': 'FI'},
{'code3': 'FJI', 'name': 'Fiji', 'value': 5.67, 'code': 'FJ'},
{'code3': 'FRA', 'name': 'France', 'value': 6.25, 'code': 'FR'},
{'code3': 'FRO', 'name': 'Faroe Islands', 'value': 6.4, 'code': 'FO'},
{'code3': 'FSM',
 'name': 'Micronesia, Fed. Sts.',
 'value': 'No Data',
 'code': 'FM'},
{'code3': 'GAB', 'name': 'Gabon', 'value': 4.5, 'code': 'GA'},
{'code3': 'GBR', 'name': 'United Kingdom', 'value': 5.94, 'code': 'GB'},
{'code3': 'GEO', 'name': 'Georgia', 'value': 6.86, 'code': 'GE'},
{'code3': 'GHA', 'name': 'Ghana', 'value': 5.9, 'code': 'GH'},
{'code3': 'GIB', 'name': 'Gibraltar', 'value': 4.2, 'code': 'GI'},
{'code3': 'GIN', 'name': 'Guinea', 'value': 6.35, 'code': 'GN'},
{'code3': 'GMB', 'name': 'Gambia, The', 'value': 'No Data', 'code': 'GM'},
{'code3': 'GNB', 'name': 'Guinea-Bissau', 'value': 6.4, 'code': 'GW'},
{'code3': 'GNQ', 'name': 'Equatorial Guinea', 'value': 5.5, 'code': 'GQ'},
{'code3': 'GRC', 'name': 'Greece', 'value': 6.11, 'code': 'GR'},
{'code3': 'GRD', 'name': 'Grenada', 'value': 'No Data', 'code': 'GD'},
{'code3': 'GRL', 'name': 'Greenland', 'value': 6.34, 'code': 'GL'},
{'code3': 'GTM', 'name': 'Guatemala', 'value': 6.58, 'code': 'GT'},
{'code3': 'GUM', 'name': 'Guam', 'value': 'No Data', 'code': 'GU'},
{'code3': 'GUY', 'name': 'Guyana', 'value': 'No Data', 'code': 'GY'},
{'code3': 'HKG',
 'name': 'Hong Kong SAR, China',
 'value': 'No Data',
 'code': 'HK'},
{'code3': 'HND', 'name': 'Honduras', 'value': 6.33, 'code': 'HN'},
{'code3': 'HRV', 'name': 'Croatia', 'value': 6.44, 'code': 'HR'},
{'code3': 'HTI', 'name': 'Haiti', 'value': 6.0, 'code': 'HT'},
{'code3': 'HUN', 'name': 'Hungary', 'value': 6.33, 'code': 'HU'},
{'code3': 'IDN', 'name': 'Indonesia', 'value': 6.34, 'code': 'ID'},
{'code3': 'IMN', 'name': 'Isle of Man', 'value': 'No Data', 'code': 'IM'},
{'code3': 'IND', 'name': 'India', 'value': 6.22, 'code': 'IN'},
{'code3': 'IRL', 'name': 'Ireland', 'value': 6.04, 'code': 'IE'},
{'code3': 'IRN',
 'name': 'Iran, Islamic Rep.',
 'value': 5.92,
 'code': 'IR'},
{'code3': 'IRQ', 'name': 'Iraq', 'value': 6.52, 'code': 'IQ'},
{'code3': 'ISL', 'name': 'Iceland', 'value': 6.32, 'code': 'IS'},
{'code3': 'ISR', 'name': 'Israel', 'value': 6.25, 'code': 'IL'},
{'code3': 'ITA', 'name': 'Italy', 'value': 6.01, 'code': 'IT'},
{'code3': 'JAM', 'name': 'Jamaica', 'value': 6.35, 'code': 'JM'},
{'code3': 'JOR', 'name': 'Jordan', 'value': 6.42, 'code': 'JO'},
{'code3': 'JPN', 'name': 'Japan', 'value': 6.49, 'code': 'JP'},
{'code3': 'KAZ', 'name': 'Kazakhstan', 'value': 6.38, 'code': 'KZ'},
{'code3': 'KEN', 'name': 'Kenya', 'value': 6.42, 'code': 'KE'},
{'code3': 'KGZ', 'name': 'Kyrgyz Republic', 'value': 6.71, 'code': 'KG'},
{'code3': 'KHM', 'name': 'Cambodia', 'value': 6.23, 'code': 'KH'},
{'code3': 'KIR', 'name': 'Kiribati', 'value': 'No Data', 'code': 'KI'},
{'code3': 'KNA',
 'name': 'St. Kitts and Nevis',
 'value': 'No Data',
 'code': 'KN'},
{'code3': 'KOR', 'name': 'Korea, Rep.', 'value': 6.33
, 'code': 'KR'},
{'code3': 'KWT', 'name': 'Kuwait', 'value': 7.06, 'code': 'KW'},
{'code3': 'LAO', 'name': 'Lao PDR', 'value': 6.73, 'code': 'LA'},
{'code3': 'LBN', 'name': 'Lebanon', 'value': 6.44, 'code': 'LB'},
{'code3': 'LBR', 'name': 'Liberia', 'value': 6.45, 'code': 'LR'},
{'code3': 'LBY', 'name': 'Libya', 'value': 8.3, 'code': 'LY'},
{'code3': 'LCA', 'name': 'St. Lucia', 'value': 'No Data', 'code': 'LC'},
{'code3': 'LIE', 'name': 'Liechtenstein', 'value': 5.4, 'code': 'LI'},
{'code3': 'LKA', 'name': 'Sri Lanka', 'value': 7.18, 'code': 'LK'},
{'code3': 'LSO', 'name': 'Lesotho', 'value': 7.1, 'code': 'LS'},
{'code3': 'LTU', 'name': 'Lithuania', 'value': 6.28, 'code': 'LT'},
{'code3': 'LUX', 'name': 'Luxembourg', 'value': 6.01, 'code': 'LU'},
{'code3': 'LVA', 'name': 'Latvia', 'value': 6.57, 'code': 'LV'},
{'code3': 'MAC',
 'name': 'Macao SAR, China',
 'value': 'No Data',
 'code': 'MO'},
{'code3': 'MAF',
 'name': 'St. Martin (French part)',
 'value': 'No Data',
 'code': 'MF'},
{'code3': 'MAR', 'name': 'Morocco', 'value': 6.31, 'code': 'MA'},
{'code3': 'MCO', 'name': 'Monaco', 'value': 6.06, 'code': 'MC'},
{'code3': 'MDA', 'name': 'Moldova', 'value': 7.5, 'code': 'MD'},
{'code3': 'MDG', 'name': 'Madagascar', 'value': 'No Data', 'code': 'MG'},
{'code3': 'MDV', 'name': 'Maldives', 'value': 4.0, 'code': 'MV'},
{'code3': 'MEX', 'name': 'Mexico', 'value': 6.03, 'code': 'MX'},
{'code3': 'MHL',
 'name': 'Marshall Islands',
 'value': 'No Data',
 'code': 'MH'},
{'code3': 'MKD', 'name': 'Macedonia, FYR', 'value': 6.82, 'code': 'MK'},
{'code3': 'MLI', 'name': 'Mali', 'value': 6.67, 'code': 'ML'},
{'code3': 'MLT', 'name': 'Malta', 'value': 5.54, 'code': 'MT'},
{'code3': 'MMR', 'name': 'Myanmar', 'value': 6.97, 'code': 'MM'},
{'code3': 'MNE', 'name': 'Montenegro', 'value': 6.09, 'code': 'ME'},
{'code3': 'MNG', 'name': 'Mongolia', 'value': 6.61, 'code': 'MN'},
{'code3': 'MNP',
 'name': 'Northern Mariana Islands',
 'value': 'No Data',
 'code': 'MP'},
{'code3': 'MOZ', 'name': 'Mozambique', 'value': 6.37, 'code': 'MZ'},
{'code3': 'MRT', 'name': 'Mauritania', 'value': 6.96, 'code': 'MR'},
{'code3': 'MUS', 'name': 'Mauritius', 'value': 5.7, 'code': 'MU'},
{'code3': 'MWI', 'name': 'Malawi', 'value': 7.6, 'code': 'MW'},
{'code3': 'MYS', 'name': 'Malaysia', 'value': 5.96, 'code': 'MY'},
{'code3': 'NAM', 'name': 'Namibia', 'value': 6.15, 'code': 'NA'},
{'code3': 'NCL', 'name': 'New Caledonia', 'value': 6.9, 'code': 'NC'},
{'code3': 'NER', 'name': 'Niger', 'value': 7.0, 'code': 'NE'},
{'code3': 'NGA', 'name': 'Nigeria', 'value': 5.52, 'code': 'NG'},
{'code3': 'NIC', 'name': 'Nicaragua', 'value': 6.5, 'code': 'NI'},
{'code3': 'NLD', 'name': 'Netherlands', 'value': 6.18, 'code': 'NL'},
{'code3': 'NOR', 'name': 'Norway', 'value': 6.04, 'code': 'NO'},
{'code3': 'NPL', 'name': 'Nepal', 'value': 6.9, 'code': 'NP'},
{'code3': 'NRU', 'name': 'Nauru', 'value': 'No Data', 'code': 'NR'},
{'code3': 'NZL', 'name': 'New Zealand', 'value': 6.02, 'code': 'NZ'},
{'code3': 'OMN', 'name': 'Oman', 'value': 7.0, 'code': 'OM'},
{'code3': 'PAK', 'name': 'Pakistan', 'value': 6.54, 'code': 'PK'},
{'code3': 'PAN', 'name': 'Panama', 'value': 6.51, 'code': 'PA'},
{'code3': 'PER', 'name': 'Peru', 'value': 5.91, 'code': 'PE'},
{'code3': 'PHL', 'name': 'Philippines', 'value': 5.9, 'code': 'PH'},
{'code3': 'PLW', 'name': 'Palau', 'value': 'No Data', 'code': 'PW'},
{'code3': 'PNG', 'name': 'Papua New Guinea', 'value': 7.1, 'code': 'PG'},
{'code3': 'POL', 'name': 'Poland', 'value': 6.12, 'code': 'PL'},
{'code3': 'PRI', 'name': 'Puerto Rico', 'value': 5.93, 'code': 'PR'},
{'code3': 'PRK',
 'name': 'Korea, Dem. People’s Rep.',
 'value': 5.75,
 'code': 'KP'},
{'code3': 'PRT', 'name': 'Portugal', 'value': 6.19, 'code': 'PT'},
{'code3': 'PRY', 'name': 'Paraguay', 'value': 6.57, 'code': 'PY'},
{'code3': 'PSE',
 'name': 'West Bank and Gaza',
 'value': 'No Data',
 'code': 'PS'},
{'code3': 'PYF',
 'name': 'French Polynesia',
 'value': 'No Data',
 'code': 'PF'},
{'code3': 'QAT', 'name': 'Qatar', 'value': 6.62, 'code': 'QA'},
{'code3': 'ROU', 'name': 'Romania', 'value': 6.59, 'code': 'RO'},
{'code3': 'RUS',
 'name': 'Russian Federation',
 'value': 5.74,
 'code': 'RU'},
{'code3': 'RWA', 'name': 'Rwanda', 'value': 5.62, 'code': 'RW'},
{'code3': 'SAU', 'name': 'Saudi Arabia', 'value': 6.26, 'code': 'SA'},
{'code3': 'SDN', 'name': 'Sudan', 'value': 6.6, 'code': 'SD'},
{'code3': 'SEN', 'name': 'Senegal', 'value': 6.86, 'code': 'SN'},
{'code3': 'SGP', 'name': 'Singapore', 'value': 6.0, 'code': 'SG'},
{'code3': 'SLB', 'name': 'Solomon Islands', 'value': 'No Data', 'code': 'SB'},
{'code3': 'SLE', 'name': 'Sierra Leone', 'value': 'No Data', 'code': 'SL'},
{'code3': 'SLV', 'name': 'El Salvador', 'value': 4.5, 'code': 'SV'},
{'code3': 'SMR', 'name': 'San Marino', 'value': 'No Data', 'code': 'SM'},
{'code3': 'SOM', 'name': 'Somalia', 'value': 6.6, 'code': 'SO'},
{'code3': 'SRB', 'name': 'Serbia', 'value': 6.31, 'code': 'RS'},
{'code3': 'STP',
 'name': 'Sao Tome and Principe',
 'value': 'No Data',
 'code': 'ST'},
{'code3': 'SUR', 'name': 'Suriname', 'value': 6.9, 'code': 'SR'},
{'code3': 'SVK', 'name': 'Slovak Republic', 'value': 6.31, 'code': 'SK'},
{'code3': 'SVN', 'name': 'Slovenia', 'value': 6.56, 'code': 'SI'},
{'code3': 'SWE', 'name': 'Sweden', 'value': 5.9, 'code': 'SE'},
{'code3': 'SWZ', 'name': 'Swaziland', 'value': 6.9, 'code': 'SZ'},
{'code3': 'SXM',
 'name': 'Sint Maarten (Dutch part)',
 'value': 'No Data',
 'code': 'SX'},
{'code3': 'SYC', 'name': 'Seychelles', 'value': 'No Data', 'code': 'SC'},
{'code3': 'SYR',
 'name': 'Syrian Arab Republic',
 'value': 6.22,
 'code': 'SY'},
{'code3': 'TCA',
 'name': 'Turks and Caicos Islands',
 'value': 'No Data',
 'code': 'TC'},
{'code3': 'TCD', 'name': 'Chad', 'value': 6.6, 'code': 'TD'},
{'code3': 'TGO', 'name': 'Togo', 'value': 'No Data', 'code': 'TG'},
{'code3': 'THA', 'name': 'Thailand', 'value': 5.83, 'code': 'TH'},
{'code3': 'TJK', 'name': 'Tajikistan', 'value': 6.62, 'code': 'TJ'},
{'code3': 'TKM', 'name': 'Turkmenistan', 'value': 'No Data', 'code': 'TM'},
{'code3': 'TLS', 'name': 'Timor-Leste', 'value': 'No Data', 'code': 'TL'},
{'code3': 'TON', 'name': 'Tonga', 'value': 'No Data', 'code': 'TO'},
{'code3': 'TTO', 'name': 'Trinidad and Tobago', 'value': 5.55, 'code': 'TT'},
{'code3': 'TUN', 'name': 'Tunisia', 'value': 6.58, 'code': 'TN'},
{'code3': 'TUR', 'name': 'Turkey', 'value': 5.87, 'code': 'TR'},
{'code3': 'TUV', 'name': 'Tuvalu', 'value': 'No Data', 'code': 'TV'},
{'code3': 'TZA', 'name': 'Tanzania', 'value': 6.4, 'code': 'TZ'},
{'code3': 'UGA', 'name': 'Uganda', 'value': 7.12, 'code': 'UG'},
{'code3': 'UKR', 'name': 'Ukraine', 'value': 6.4, 'code': 'UA'},
{'code3': 'URY', 'name': 'Uruguay', 'value': 6.41, 'code': 'UY'},
{'code3': 'USA', 'name': 'United States', 'value': 5.61, 'code': 'US'},
{'code3': 'UZB', 'name': 'Uzbekistan', 'value': 6.95, 'code': 'UZ'},
{'code3': 'VCT',
 'name': 'St. Vincent and the Grenadines',
 'value': 'No Data',
 'code': 'VC'},
{'code3': 'VEN', 'name': 'Venezuela, RB', 'value': 6.38, 'code': 'VE'},
{'code3': 'VGB',
 'name': 'British Virgin Islands',
 'value': 6.45,
 'code': 'VG'},
{'code3': 'VIR',
 'name': 'Virgin Islands (U.S.)',
 'value': 'No Data',
 'code': 'VI'},
{'code3': 'VNM', 'name': 'Vietnam', 'value': 6.6, 'code': 'VN'},
{'code3': 'VUT', 'name': 'Vanuatu', 'value': 6.9, 'code': 'VU'},
{'code3': 'WSM', 'name': 'Samoa', 'value': 7.0, 'code': 'WS'},
{'code3': 'YEM', 'name': 'Yemen, Rep.', 'value': 7.02, 'code': 'YE'},
{'code3': 'ZAF', 'name': 'South Africa', 'value': 5.56, 'code': 'ZA'},
{'code3': 'ZMB', 'name': 'Zambia', 'value': 5.53, 'code': 'ZM'},
{'code3': 'ZWE', 'name': 'Zimbabwe', 'value': 6.45, 'code': 'ZW'}]

Highcharts.mapChart("map", {

    chart: {
        map: 'custom/world',
        backgroundColor: "#faebd7"
    },

    title: {
        text: "Average Rating per Country"
    },

    legend: {
        title: {
            text: 'Average Movie Rating',
            style: {
                color: ( // theme
                    Highcharts.defaultOptions &&
                    Highcharts.defaultOptions.legend &&
                    Highcharts.defaultOptions.legend.title &&
                    Highcharts.defaultOptions.legend.title.style &&
                    Highcharts.defaultOptions.legend.title.style.color
                ) || 'black'
            }
        }
    },

    mapNavigation: {
        enabled: true,
        buttonOptions: {
            verticalAlign: 'bottom'
        }
    },

    tooltip: {
        backgroundColor: 'none',
        borderWidth: 0,
        shadow: false,
        useHTML: true,
        padding: 0,
        pointFormat: 
            '</span></span> {point.name}<br>' +
            '<span style="font-size:30px">{point.value}</span>',
        positioner: function () {
            return { x: 250, y: 250 };
        }
    },

    colorAxis: {
        min: 1,
        max: 10,
        type: 'logarithmic'
    },

    plotOptions: {
        series: {
            states: {
                hover: {
                    color: "#F8C471"
            }},
        }
    },

    colorAxis: {
        min: 0,
        minColor: "#F5B7B1",
        maxColor: "#943126"
    },

    series: [{
        data: data3,
        joinBy: ['iso-a3', 'code3'],
        name: 'Average Rating'

    }]
});